#==========================================================================
# Description: Build Armbian arm64 with custom DTS for x3399-9tripod
#==========================================================================

name: Build x3399 Custom Armbian IMG

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      set_release:
        description: "Select OS Release."
        required: false
        default: "bookworm"
        type: choice
        options:
          - trixie
          - bookworm
      armbian_kernel:
        description: "Select kernel version."
        required: false
        default: "6.1.y"
        type: choice
        options:
          - 5.15.y
          - 6.1.y
          - 6.6.y
          - 6.12.y
      kernel_usage:
        description: "Set the tags of the kernel."
        required: false
        default: "stable"
        type: choice
        options:
          - stable
          - beta
      armbian_fstype:
        description: "Select armbian rootfs type."
        required: false
        default: "ext4"
        type: choice
        options:
          - ext4
          - btrfs

env:
  TZ: Etc/UTC
  CUSTOM_DTS_PATH: custom-dts
  MODEL_DB_PATH: build-armbian/armbian-files/common-files/etc/model_database.conf
  KERNEL_TAGS: stable

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Initialize build environment
        id: init
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi -f $(docker images -q) 2>/dev/null || true
          [[
